### ISSUE TITLE
Unable to construct iterable assertions across a specific type easily

### ISSUE THREAD

**Issue by ascopes** [assertj/assertj#3490]
Within the new AssertJ 3.26.0 release, I can see that the factory based navigable assertion for iterables has been deprecated internally, along with other mechanisms to do the same thing.

This raises an issue for me, as I extend the AssertJ API and provide additional custom assertions that wrap the assertj ones.

In this case, I have a requirement to be able to return an assertion object across a list of strings for the user to be able to perform further assertions on. The current implementation looks like this: https://github.com/ascopes/java-compiler-testing/blob/1a92ef59df49cf2f45ae83a109569be006b08df2/java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/JctCompilationAssert.java#L70.

Unfortunately with these APIs being deprecated, I can not find a way to return an iterable assert across strings that automatically expand to string assertions. I can see new API methods such as .first(AssertFactory) and last(AssertFactory), but no way to instruct AssertJ how to expose assertions on internal objects anymore such that the user does not need to explicitly cast these assertions with an explicit InstanceOfAssertFactory object.

Is there any advice for how to migrate off of this, or is this something that will need to be a breaking API change on my side?

**Comment by scordio** [comment]
Thanks for your feedback, @ascopes!

Please give me a bit of time to get familiar with your use case – I'll get back to you.

**Comment by scordio** [comment]
Although it's possible to obtain the previous behavior, similar to how you did it with [`TypeAwareListAssert`](https://github.com/ascopes/java-compiler-testing/blob/74704bcdc58ebca669557c9d27a5f22b8c37fb1d/java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/TypeAwareListAssert.java), I believe we should provide better support for such use cases.

However, I wouldn't reintroduce what we've been deprecating as it's less discoverable.

What if we would add an API to configure the assertions for the available navigation methods? 

Something like:

```java
assertThat(List.of("a", "b", "c"))
  .withElementAssert(StringAssert::new)
  // further assertions on the list
  .hasSize(3)
  // navigation method
  .first() // returns StringAssert instead of ObjectAssert<String>
  // further String assertions on the element
  ...
```

Then, your example would become:

```java
public AbstractListAssert<?, List<? extends String>, String, ? extends AbstractStringAssert<?>> arguments() {
  isNotNull();

  var arguments = actual.getArguments();

  return Assertions.assertThat(arguments)
      .withElementAssert(StringAssert::new)
      .as("Compiler arguments %s", StringUtils.quotedIterable(arguments));
}
```

**Comment by ascopes** [comment]
This sounds like a very good idea, and would be very helpful! I struggled with getting generics to work consistently for this so any help would be greatly appreciated.

**Comment by scordio** [comment]
Would it be okay if we introduce such a change in 3.27.0?

I'd prefer having enough time to digest it properly, and the deprecations aren't going anywhere, at least until version 4.

**Comment by ascopes** [comment]
Sounds sensible to me! I'd need to release a new version to change to a new API anyway so there is no rush

**Comment by Adrodoc55** [comment]
I also heavily use `FactoryBasedNavigableListAssert` and love the proposal for `withElementAssert`. I actually wanted to open an issue for improving the generics, but then saw this issue about it beeing deprecated. So I'll post here.

Currently `FactoryBasedNavigableListAssert` and by extension the deprecated assertThat method requires the `ELEMENT_ASSERT` to extend `AbstractAssert<ELEMENT_ASSERT, ELEMENT>`. This sounds reasonable at first and works fine for concrete assert classes, but the bound is too tight for generic assert classes such as abstract ones.

Consider the following example:
```java
import java.util.List;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.AbstractIntegerAssert;
import org.assertj.core.api.AssertFactory;
import org.assertj.core.api.Assertions;
import org.assertj.core.api.ClassAssert;
import org.assertj.core.api.FactoryBasedNavigableListAssert;

public class Test {
  public static void main(String[] args) {
    List<Class<?>> actualClasses = List.of(Integer.class);
    ClassAssert classAsserter1 = Assertions.assertThat(actualClasses.get(0));
    ClassAssert classAsserter2 = Assertions.assertThat(actualClasses, Assertions::assertThat).element(0);
    ClassAssert classAsserter3 = assertThat2(actualClasses, Assertions::assertThat).element(0);

    List<Integer> actualIntegers = List.of(0);
    AbstractIntegerAssert<?> integerAsserter1 = Assertions.assertThat(actualIntegers.get(0));
    AbstractIntegerAssert<?> integerAsserter2 =
        Assertions.assertThat(actualIntegers, Assertions::assertThat).element(0);
    AbstractIntegerAssert<?> integerAsserter3 = assertThat2(actualIntegers, Assertions::assertThat).element(0);
  }

  public static <ACTUAL extends List<? extends ELEMENT>, ELEMENT, ELEMENT_ASSERT extends AbstractAssert<? extends ELEMENT_ASSERT, ELEMENT>> FactoryBasedNavigableListAssert<?, ACTUAL, ELEMENT, ELEMENT_ASSERT> assertThat2(
      List<? extends ELEMENT> actual, AssertFactory<ELEMENT, ELEMENT_ASSERT> assertFactory) {
    return null;
  }
}
```

For the `List<Class<?>>` everything works fine, because `assertThat(Class<?> actual)` returns the non-generic type `ClassAssert`, but for integers it does not compile. The reason is that `AbstractIntegerAssert<?>` which is the return type of `assertThat(Integer actual)` does not satisfy the bound i mentioned above: `AbstractAssert<ELEMENT_ASSERT, ELEMENT>`. The bound should really be `AbstractAssert<? extends ELEMENT_ASSERT, ELEMENT>`. To prove this change makes it work I added the method `assertThat2` in the example. This method doesn't compile because the incorrect upper bound also appears in the declaration of `FactoryBasedNavigableListAssert` and its superclasses, but the call to assertThat2 does compile.

**Comment by scordio** [comment]
Thanks a lot for your feedback, @Adrodoc55. I'll keep that in mind!

**Comment by scordio** [comment]
Hi, @ascopes, We would like to release 3.27.0 soon, and I've been working on this issue for the last few days.

However, there is one more detail I'd like to digest better before adding this feature. As soon as I'm done with it, we'll consider releasing 3.28.0 soon so we don't keep you waiting too long.

**Comment by ascopes** [comment]
@scordio thanks for letting me know, and no rush!

**Comment by scordio** [comment]
@ascopes would it be a problem if we deliver this in version 4?

**Comment by ascopes** [comment]
Go for it.

https://github.com/ascopes/java-compiler-testing/blob/main/java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/TypeAwareListAssert.java I have a workaround for now (albeit a hacky one).

**Comment by scordio** [comment]
@ascopes @Adrodoc55 just FYI, I started working on #4076 and it looks promising so far.

If I manage to bring it into good shape over the next few days, I'll include it in 3.28.

In case you have time to give it a spin, please let me know!

**Comment by Adrodoc55** [comment]
@scordio I gave aaa958f3c a spin and it worked great. The example I posted above which didn't compile now works great when switching to `withElementAssert`. In my real project I was able to simply replace the following (which I have in several places):
```java
assertThat(actual.rows(), this::assertThat).as(description("rows"))
```
with this:
```java
assertThat(actual.rows()).withElementAssert(this::assertThat).as(description("rows"))
```
and everything works out of the box.

I did have a few issues with building assertj, because cloning it on my windows 10 machine gave me this error:
```
$ git clone https://github.com/assertj/assertj.git
Cloning into 'assertj'...
remote: Enumerating objects: 173174, done.
remote: Counting objects: 100% (3890/3890), done.
remote: Compressing objects: 100% (883/883), done.
remote: Total 173174 (delta 3384), reused 3085 (delta 2976), pack-reused 169284 (from 4)
Receiving objects: 100% (173174/173174), 52.18 MiB | 38.00 MiB/s, done.
Resolving deltas: 100% (128743/128743), done.
error: unable to create file assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/o
rg/assertj/tests/core/api/recursive/comparison/fields/ComparingSnakeOrCamelCaseFieldsRecursiveCompariso
nAssert_isEqualTo_ignoringTransientFields_Test.java: Filename too long
Updating files: 100% (5241/5241), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
But this of course has nothing to do with #4076.

After I managed to switch to the right branch calling `mvn install` failed for me with this error:
```
[ERROR] Tests run: 17343, Failures: 102, Errors: 97, Skipped: 47
```
Among others tests failed for this reason (I compiled with temurin jdk-25.0.1+8 from http://adoptium.net):
```
[ERROR]   MapAssert_extracting_Test.should_fail_with_unknown_key:89
Expecting actual throwable to be an instance of:
  org.assertj.core.util.introspection.IntrospectionError
but was:
  java.lang.Error: Unresolved compilation problem:
        The type of newObjectAssert(Object) from the type AbstractObjectAssert<SELF,ACTUAL> is Abstract
ObjectAssert<?,Object>, this is incompatible with the descriptor's return type: AbstractObjectAssert<Ab
stractObjectAssert<AbstractObjectAssert<?,Object>,Object>,Object>

        at org.assertj.core.api.AbstractObjectAssert.extracting(AbstractObjectAssert.java:803)
        at org.assertj.core.api.map.MapAssert_extracting_Test.lambda$should_fail_with_unknown_key$0(Map
Assert_extracting_Test.java:87)
        at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
        at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:905
)
        at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1473)
        at org.assertj.core.api.map.MapAssert_extracting_Test.should_fail_with_unknown_key(MapAssert_ex
tracting_Test.java:87)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.
java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:565)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:786)
        at org.junit.platform.commons.support.ReflectionSupport.invokeMethod(ReflectionSupport.java:514
)
        ...(71 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElem
entsDisplayed)
```
I then built assertj with this command which worked:
```
mvn install -pl assertj-core -am -Dmaven.test.skip
```

**Comment by scordio** [comment]
Thanks for the feedback and the details about the side issues!

> [@scordio](https://github.com/scordio) I gave [aaa958f](https://github.com/assertj/assertj/commit/aaa958f3c1460a65c85396795f4f60cb92e8f13f) a spin and it worked great. The example I posted above which didn't compile now works great when switching to `withElementAssert`.

Glad to hear it 🙂 I have some further polishing in mind, but no user-facing change should happen.

> ```
> error: unable to create file assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/fields/ComparingSnakeOrCamelCaseFieldsRecursiveComparisonAssert_isEqualTo_ignoringTransientFields_Test.java: Filename too long
> ```

Interestingly, the GitHub Actions Windows runner doesn't have this issue... I'll check how we could shorten the full path 🙂 

> ```
> java.lang.Error: Unresolved compilation problem:
>         The type of newObjectAssert(Object) from the type AbstractObjectAssert<SELF,ACTUAL> is Abstract
> ObjectAssert<?,Object>, this is incompatible with the descriptor's return type: AbstractObjectAssert<Ab
> stractObjectAssert<AbstractObjectAssert<?,Object>,Object>,Object>
> ```

This appears to be related to #3996, which I partially fixed on `main` with 3941c9e but not on `3.x`, so I'll backport that commit.

**Comment by Adrodoc55** [comment]
I just remembered something related to the generics of this API that has been bothering me for years. Maybe you want to consider it, since you're already working on the relevant class anyways. I'll try to provide some info on that tomorrow (it's very late here).

**Comment by scordio** [comment]
Sure, take your time! There's no rush.

**Comment by Adrodoc55** [comment]
So what has been bothering me for so long is already resolved by relaxing the bound on ELEMENT_ASSERT. However I am still struggling with some code.
I just can't figure out why this code does not compile:
```java
import java.util.List;
import org.assertj.core.api.AbstractCharSequenceAssert;
import org.assertj.core.api.AbstractStringAssert;
import org.assertj.core.api.AssertFactory;
import org.assertj.core.api.Assertions;
import org.assertj.core.api.AssertionsForClassTypes;

public class Main {
  public static void main(String[] args) {
    List<String> strings = List.of("hello", "world");
    AssertFactory<String, AbstractStringAssert<?>> stringAssertFactory = Assertions::assertThat;
    AssertFactory<String, AbstractStringAssert<?>> stringAssertFactory2 = Main::assertThatString;
    Assertions.assertThat(strings).withElementAssert(Assertions::assertThat);
    Assertions.assertThat(strings).withElementAssert(Main::assertThatString);
    Assertions.assertThat(strings).withElementAssert(stringAssertFactory);
    Assertions.assertThat(strings).withElementAssert(stringAssertFactory2);

    List<CharSequence> charSequences = List.of("hello", "world");
    AssertFactory<CharSequence, AbstractCharSequenceAssert<?, ?>> csAssertFactory = Assertions::assertThat;
    Assertions.assertThat(strings).withElementAssert(csAssertFactory);
  }

  public static AbstractStringAssert<?> assertThatString(String actual) {
    return AssertionsForClassTypes.assertThat(actual);
  }
}
```

**Comment by scordio** [comment]
I guess you meant the following in the last three lines of the `main` method, right?

```diff
    List<CharSequence> charSequences = List.of("hello", "world");
    AssertFactory<CharSequence, AbstractCharSequenceAssert<?, ?>> csAssertFactory = Assertions::assertThat;
-   Assertions.assertThat(strings).withElementAssert(csAssertFactory);
+   Assertions.assertThat(charSequences).withElementAssert(csAssertFactory);
```

Otherwise, `charSequences` would be unused.

Nevertheless, that doesn't compile either – I'm looking into it.

**Comment by scordio** [comment]
A more focused reproducer is:

```java
List<CharSequence> actual = List.of("hello", "world");
assertThat(actual)                            // returns ListAssert<CharSequence>
  .withElementAssert(Assertions::assertThat)  // does not compile
  .first()
  .startsWith("he");
```

which produces a compile warning:

```
Unchecked method 'withElementAssert(AssertFactory<ELEMENT, ASSERT>)' invocation 
```

and a compile error:

```
Incompatible equality constraint: CharSequence and capture of ? extends CharSequence
```

However, the following compiles without issues:

```java
List<CharSequence> actual = List.of("hello", "world");
assertThat(actual)                            // returns ListAssert<CharSequence>
  .withElementAssert(CharSequenceAssert::new) // returns AbstractListAssert<..., ..., CharSequence, CharSequenceAssert>
  .first()                                    // returns CharSequenceAssert
  .startsWith("he");
```

and also the following:

```java
List<String> actual = List.of("hello", "world");
assertThat(actual).                           // returns ListAssert<String>
  .withElementAssert(Assertions::assertThat)  // returns AbstractListAssert<..., ..., String, AbstractStringAssert> 
  .first()                                    // returns AbstractStringAssert<...>
  .startsWith("he");
```

so I'm guessing the issue is within the type parameters of the `assertThat(CharSequence)` return type declaration:

https://github.com/assertj/assertj/blob/ce33872300f773f446686a2a89407ff8c2382f9a/assertj-core/src/main/java/org/assertj/core/api/Assertions.java#L3160-L3162

I raised #4079 for further analysis, but I'm not optimistic we could improve it in version 3 without a binary-incompatible change (which we tend to avoid).

**Comment by Adrodoc55** [comment]
Ok so there are actually three separate issues here that I confused with each other. Let me give you a more complete example of what I was actually trying to do.

# Issue 1: Return Type of AbstractListAssert.withElementAssert

I also uploaded a ZIP with these example classes: [assertj-issue-3490.zip](https://github.com/user-attachments/files/24357129/assertj-issue-3490.zip)

I have two classes like these:
```java
public class Item {
  public int amount;
  public String name;
}
```
```java
import java.util.List;

public class Order {
  public List<Item> items;
  public String customerName;
}
```
The same module contains assert classes for these:
```java
import javax.annotation.CheckReturnValue;
import javax.annotation.Nullable;
import org.assertj.core.api.AbstractIntegerAssert;
import org.assertj.core.api.AbstractStringAssert;

public class ItemModule1Assert<SELF extends ItemModule1Assert<SELF>> //
    extends ExtendedAbstractObjectAssert<SELF, Item> //
    implements Module1AssertFactory {
  public ItemModule1Assert(@Nullable Item actual) {
    super(actual, ItemModule1Assert.class);
  }

  protected ItemModule1Assert(@Nullable Item actual, Class<?> selfType) {
    super(actual, selfType);
  }

  @CheckReturnValue
  public AbstractIntegerAssert<?> amount() {
    return assertThat(actual.amount).as(description("amount"));
  }

  @CheckReturnValue
  public AbstractStringAssert<?> name() {
    return assertThat(actual.name).as(description("name"));
  }
}
```
```java
import javax.annotation.CheckReturnValue;
import javax.annotation.Nullable;
import org.assertj.core.api.AbstractListAssert;
import org.assertj.core.api.AbstractStringAssert;

public class OrderModule1Assert<SELF extends OrderModule1Assert<SELF>> //
    extends ExtendedAbstractObjectAssert<SELF, Order> //
    implements Module1AssertFactory {
  public OrderModule1Assert(@Nullable Order actual) {
    super(actual, OrderModule1Assert.class);
  }

  protected OrderModule1Assert(@Nullable Order actual, Class<?> selfType) {
    super(actual, selfType);
  }

  @CheckReturnValue
  public AbstractStringAssert<?> customerName() {
    return assertThat(actual.customerName).as(description("customerName"));
  }

  @CheckReturnValue
  public AbstractListAssert<?, ?, Item, ? extends ItemModule1Assert<?>> items() {
    return assertThat(actual.items).as(description("items")).withElementAssert(this::assertThat);
  }
}
```
For completeness here is our custom super class:
```java
import javax.annotation.Nullable;
import org.assertj.core.api.AbstractObjectAssert;

public class ExtendedAbstractObjectAssert<SELF extends ExtendedAbstractObjectAssert<SELF, ACTUAL>, ACTUAL>
    extends AbstractObjectAssert<SELF, ACTUAL> implements ExtendedAssert<SELF, ACTUAL> {
  protected ExtendedAbstractObjectAssert(@Nullable ACTUAL actual, Class<?> selfType) {
    super(actual, selfType);
  }
}
```
```java
import org.assertj.core.api.Assert;
import com.google.common.base.Strings;

public interface ExtendedAssert<SELF extends ExtendedAssert<SELF, ACTUAL>, ACTUAL> extends Assert<SELF, ACTUAL> {
  String descriptionText();

  default String description() {
    String descriptionText = descriptionText();
    return Strings.isNullOrEmpty(descriptionText) ? "actual" : descriptionText;
  }

  default String description(String description, Object... args) {
    return description() + "." + String.format(description, args);
  }

  default String navigationDescription(Object description, Object... args) {
    return description() + "[" + String.format(String.valueOf(description), args) + "]";
  }
}
```
These are available through a custom assert factory:
```java
import javax.annotation.CheckReturnValue;
import javax.annotation.Nullable;
import org.assertj.core.api.WithAssertions;

public interface Module1AssertFactory extends WithAssertions {
  @CheckReturnValue
  default ItemModule1Assert<?> assertThat(@Nullable Item actual) {
    return new ItemModule1Assert<>(actual);
  }

  @CheckReturnValue
  default OrderModule1Assert<?> assertThat(@Nullable Order actual) {
    return new OrderModule1Assert<>(actual);
  }
}
```
The interesting part here is the method `OrderModule1Assert.items()`. This is impossible to implement with current assertj, but with the new `withElementAssert` this works due to the relaxed bound on `ELEMENT_ASSERT`. This is what has been bothering me for years, but which now works. But now on to the new issue. The code architecture is this way to allow a second module to extend the assert classes:
```java
import javax.annotation.Nullable;

public class ItemModule2Assert<SELF extends ItemModule2Assert<SELF>> //
    extends ItemModule1Assert<SELF> //
    implements Module2AssertFactory {
  public ItemModule2Assert(@Nullable Item actual) {
    super(actual, ItemModule2Assert.class);
  }

  protected ItemModule2Assert(@Nullable Item actual, Class<?> selfType) {
    super(actual, selfType);
  }
}
```
```java
import javax.annotation.Nullable;
import org.assertj.core.api.AbstractListAssert;

public class OrderModule2Assert<SELF extends OrderModule2Assert<SELF>> //
    extends OrderModule1Assert<SELF> //
    implements Module2AssertFactory {
  public OrderModule2Assert(@Nullable Order actual) {
    super(actual, OrderModule2Assert.class);
  }

  protected OrderModule2Assert(@Nullable Order actual, Class<?> selfType) {
    super(actual, selfType);
  }

  @Override
  public AbstractListAssert<?, ?, Item, ? extends ItemModule2Assert<?>> items() {
    return super.items().withElementAssert(this::assertThat);
  }
}
```
These are again made available through an assert factory:
```java
import javax.annotation.CheckReturnValue;
import javax.annotation.Nullable;

public interface Module2AssertFactory extends Module1AssertFactory {
  @Override
  @CheckReturnValue
  default ItemModule2Assert<?> assertThat(@Nullable Item actual) {
    return new ItemModule2Assert<>(actual);
  }

  @Override
  @CheckReturnValue
  default OrderModule2Assert<?> assertThat(@Nullable Order actual) {
    return new OrderModule2Assert<>(actual);
  }
}
```
Now the method `OrderModule2Assert.items()` does not compile. I first thought this was a generics issue, but it turns out this is actually an issue with the raw return type. As a workaround the code can be fixed by replacing all occurences of `AbstractListAssert` with `AbstractCollectionAssert`. However this should really be fixed in AssertJ by adding an override of `withElementAssert` to `AbstractListAssert` that returns a `AbstractListAssert`, similar to `AbstractCollectionAssert.withElementAssert` which returns an `AbstractCollectionAssert`. I don't quite understand, why you chose to implement `withElementAssert` in `FactoryBasedNavigableListAssert` and not in `AbstractListAssert` in the first place. This seems inconsistent with `AbstractCollectionAssert.withElementAssert`. I think you should do one of the following:
1. Move `FactoryBasedNavigableListAssert.withElementAssert` to `AbstractListAssert` and `FactoryBasedNavigableIterableAssert.withElementAssert` to `AbstractIterableAssert`.
2. Make `AbstractCollectionAssert.withElementAssert` abstract and move the implementation to `CollectionAssert` and add the method `public abstract <ASSERT extends AbstractAssert<? extends ASSERT, ELEMENT>> AbstractListAssert<?, ACTUAL, ELEMENT, ASSERT> withElementAssert(AssertFactory<ELEMENT, ASSERT> assertFactory);` to `AbstractListAssert`.

# Issue 2: withElementAssert does not compile in eclipsec

So completely unrelated to the first issue the following code does not compile. This was what I was getting at in my comment: https://github.com/assertj/assertj/issues/3490#issuecomment-3689845327
It turns out this is actually a bug in `eclipsec`, because this code compiles just fine with `javac`. So there is nothing assertj can do here.

```java
import java.util.List;
import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.api.AbstractStringAssert;
import org.assertj.core.api.AssertFactory;
import org.assertj.core.api.Assertions;

public class Main {
  public static void main(String[] args) {
    List<String> strings = List.of("hello", "world");
    Assertions.assertThat(strings).withElementAssert(Assertions::assertThat); // works
    Assertions.assertThat(strings).withElementAssert(Main::assertThatString1); // works
    Assertions.assertThat(strings).withElementAssert(Main::assertThatString2); // works

    Assertions.assertThat(strings).withElementAssert(actual -> Assertions.assertThat(actual)); // works
    Assertions.assertThat(strings).withElementAssert(actual -> assertThatString1(actual)); // works
    Assertions.assertThat(strings).withElementAssert(actual -> assertThatString2(actual)); // works

    AssertFactory<String, AbstractStringAssert<?>> stringAssertFactory = Assertions::assertThat; // works
    AssertFactory<String, MyStringAssert1> stringAssertFactory1 = Main::assertThatString1; // works
    AssertFactory<String, MyStringAssert2<?>> stringAssertFactory2 = Main::assertThatString2; // works

    Assertions.assertThat(strings).withElementAssert(stringAssertFactory); // error: The method withElementAssert(AssertFactory<String,ASSERT>) in the type FactoryBasedNavigableListAssert<ListAssert<String>,List<? extends String>,String,ObjectAssert<String>> is not applicable for the arguments (AssertFactory<String,AbstractStringAssert<?>>)
    Assertions.assertThat(strings).withElementAssert(stringAssertFactory1); // works
    Assertions.assertThat(strings).withElementAssert(stringAssertFactory2); // error: The method withElementAssert(AssertFactory<String,ASSERT>) in the type FactoryBasedNavigableListAssert<ListAssert<String>,List<? extends String>,String,ObjectAssert<String>> is not applicable for the arguments (AssertFactory<String,MyStringAssert2<?>>)
  }

  public static MyStringAssert1 assertThatString1(String actual) {
    return new MyStringAssert1(actual);
  }

  public static MyStringAssert2<?> assertThatString2(String actual) {
    return new MyStringAssert2<>(actual);
  }
}

class MyStringAssert1 extends AbstractObjectAssert<MyStringAssert1, String> {
  public MyStringAssert1(String actual) {
    super(actual, MyStringAssert1.class);
  }
}

class MyStringAssert2<SELF extends MyStringAssert2<SELF>> extends AbstractObjectAssert<SELF, String> {
  public MyStringAssert2(String actual) {
    this(actual, MyStringAssert2.class);
  }

  protected MyStringAssert2(String actual, Class<?> selfType) {
    super(actual, selfType);
  }
}
```

# Issue 3: withElementAssert doesn't work with CharSequence

And last we have #4079. Originally I didn't even realize there was an issue specific to `CharSequence`, I actually just wanted to use `CharSequence` to show issue 2. It's good that you spotted this.
In my opinion this declaration:
```java
public static AbstractCharSequenceAssert<?, ? extends CharSequence> assertThat(CharSequence actual) {
  return AssertionsForInterfaceTypes.assertThat(actual);
}
```
Should be changed to one of the following:
```java
public static AbstractCharSequenceAssert<?, CharSequence> assertThat(CharSequence actual) {
  return AssertionsForInterfaceTypes.assertThat(actual);
}
```
```java
public static <ACTUAL extends CharSequence> AbstractCharSequenceAssert<?, ACTUAL> assertThat(ACTUAL actual) {
  return AssertionsForInterfaceTypes.assertThat(actual);
}
```
I think the second option would be better, because it allows using `withElementAssert` on something like `List<StringBuilder>` as `StringBuilder` implements `CharSequence`:
```java
import java.util.List;
import org.assertj.core.api.AbstractCharSequenceAssert;
import org.assertj.core.api.AbstractListAssert;
import org.assertj.core.api.AbstractStringAssert;
import org.assertj.core.api.Assertions;
import org.assertj.core.api.ObjectAssert;

public class Main {
  public static void main(String[] args) {
    List<CharSequence> charSequences = List.of("hello", "world");
    AbstractListAssert<?, List<? extends CharSequence>, CharSequence, AbstractCharSequenceAssert<?, CharSequence>> a1 =
        Assertions.assertThat(charSequences).withElementAssert(Main::assertThatNonGeneric); // works
    AbstractListAssert<?, List<? extends CharSequence>, CharSequence, AbstractCharSequenceAssert<?, CharSequence>> a2 =
        Assertions.assertThat(charSequences).withElementAssert(Main::assertThatGeneric); // works

    List<StringBuilder> stringBuilders = List.of(new StringBuilder("hello"), new StringBuilder("world"));
    Assertions.assertThat(stringBuilders).withElementAssert(Main::assertThatNonGeneric); // error: incompatible types
    AbstractListAssert<?, List<? extends StringBuilder>, StringBuilder, AbstractCharSequenceAssert<?, StringBuilder>> a4 =
        Assertions.assertThat(stringBuilders).withElementAssert(Main::assertThatGeneric); // works
  }

  public static ObjectAssert<Object> assertThatNonGeneric(Object actual) {
    return Assertions.assertThat(actual);
  }

  public static AbstractStringAssert<?> assertThatNonGeneric(String actual) {
    return Assertions.assertThat(actual);
  }

  public static AbstractCharSequenceAssert<?, CharSequence> assertThatNonGeneric(CharSequence actual) {
    return new MyCharSequenceAssert<>(actual);
  }

  public static ObjectAssert<Object> assertThatGeneric(Object actual) {
    return Assertions.assertThat(actual);
  }

  public static AbstractStringAssert<?> assertThatGeneric(String actual) {
    return Assertions.assertThat(actual);
  }

  public static <ACTUAL extends CharSequence> AbstractCharSequenceAssert<?, ACTUAL> assertThatGeneric(ACTUAL actual) {
    return new MyCharSequenceAssert<>(actual);
  }

  public static class MyCharSequenceAssert<SELF extends MyCharSequenceAssert<SELF, ACTUAL>, ACTUAL extends CharSequence>
      extends AbstractCharSequenceAssert<SELF, ACTUAL> {
    public MyCharSequenceAssert(ACTUAL actual) {
      this(actual, MyCharSequenceAssert.class);
    }

    protected MyCharSequenceAssert(ACTUAL actual, Class<?> selfType) {
      super(actual, selfType);
    }
  }
}
```
Honestly it might be a good idea to use generic type parameters for most `assertThat`-methods not just the `CharSequence` overload, as the same argument applies to all interfaces and non-final classes. However i am not sure if this might confuse the compiler in some situations. I think overload resolution should generally still find the correct methods, even when excessively using generic type parameters here, but i am aware of weird compiler bugs regarding generics. For example one bug that I encountered with `assertThat` overloads in the past is [JDK-8328617](https://bugs.openjdk.org/browse/JDK-8328617) which sadly got closed as "Not an Issue" 😞. Another thing to consider is compile times which might get worse when using a lot of generics (see also #2385) (I am specifically mentioning compile times, because this is a real issue we are currently investigating with assertj. My real project takes 5m30s to compile, which I was able to shorten to 1m30s by changing how we use assertj, but we are not yet happy with the API of our changes). So I think the generic option should be chosen, but with care.

Ok now I have rambled on for long enough, I hope all this is helpful to you @scordio.

**Comment by scordio** [comment]
Thanks for all the details, @Adrodoc55! I'll process them and get back to you.

> I don't quite understand, why you chose to implement `withElementAssert` in `FactoryBasedNavigableListAssert` and not in `AbstractListAssert` in the first place. This seems inconsistent with `AbstractCollectionAssert.withElementAssert`.

That's likely an oversight on my end. I'll fix it.

**Comment by scordio** [comment]
> Issue 1: Return Type of AbstractListAssert.withElementAssert

This should now be fixed with 1bb32248f69d6582b8bc21828330c6915135ccac.

Your examples helped me rewrite my tests so that I could reproduce the issue before fixing it. Thank you for providing them!

**Comment by scordio** [comment]
@ascopes @Adrodoc55 just FYI, I consider #4076 functionally ready: I plan to create a couple of follow-up tasks before the merge, but I don't plan any more changes unless you see further use cases that don't work and we haven't discussed yet.

**Comment by Adrodoc55** [comment]
@scordio I tested 2daaf91c4 and it looks good to me. I think you did a great Job on the API and this removes one of the very few pain points I have with AssertJ 😃

Regarding building the project:

> This appears to be related to [#3996](https://github.com/assertj/assertj/issues/3996), which I partially fixed on `main` with [3941c9e](https://github.com/assertj/assertj/commit/3941c9e7c19cf4f3a7ddb8ecba6986a01429a3c1) but not on `3.x`, so I'll backport that commit.

This seems to have worked. I get a lot less failing tests now. In case you are interested there are still failing tests, because by default on windows you need admin privileges to create symbolic links (because someone at Microsoft decided symbolic links are a security threat 🤦 this is not the first time I had this issue). Maybe it's worth mention this in [CONTRIBUTING.md](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md).
So if i run `mvn install` it fails with this:
```
[ERROR] Errors:
[ERROR]   Paths_assertEndsWithRaw_Test.should_fail_if_actual_is_not_canonical:80 ... Permission denied
[ERROR]   Paths_assertEndsWith_Test.should_pass_if_actual_is_not_canonical:97 ... Permission denied
[ERROR]   Paths_assertExistsNoFollowLinks_Test.should_pass_if_actual_is_a_symbolic_link_and_target_does_not_exist:72 ... Permission denied
[ERROR]   Paths_assertExistsNoFollowLinks_Test.should_pass_if_actual_is_a_symbolic_link_and_target_exists:63 ... Permission denied
[ERROR]   Paths_assertExists_Test.should_fail_if_actual_is_a_symbolic_link_and_target_does_not_exist:72 ... Permission denied
[ERROR]   Paths_assertExists_Test.should_pass_if_actual_is_a_symbolic_link_and_target_exists:63 ... Permission denied
[ERROR]   Paths_assertHasFileName_Test.should_pass_with_existing_symbolic_link:98 ... Permission denied
[ERROR]   Paths_assertHasNoParentRaw_Test.should_fail_if_actual_is_not_canonical:63 ... Permission denied
[ERROR]   Paths_assertHasNoParent_Test.should_pass_if_actual_is_not_canonical:80 ... Permission denied
[ERROR]   Paths_assertHasParentRaw_Test.should_fail_if_actual_is_not_canonical:92 ... Permission denied
[ERROR]   Paths_assertHasParentRaw_Test.should_fail_if_expected_is_not_canonical:103 ... Permission denied
[ERROR]   Paths_assertHasParent_Test.should_pass_if_actual_is_not_canonical:123 ... Permission denied
[ERROR]   Paths_assertHasParent_Test.should_pass_if_expected_is_not_canonical:132 ... Permission denied
[ERROR]   Paths_assertIsCanonical_Test.should_fail_if_actual_is_not_canonical:62 ... Permission denied
[ERROR]   Paths_assertIsSymbolicLink_Test.should_succeed_if_actual_is_a_symbolic_link:65 ... Permission denied
[ERROR]   Paths_assertNotExists_Test.should_fail_if_actual_is_a_symbolic_link_and_target_does_not_exist:63 ... Permission denied
[ERROR]   Paths_assertStartsWithRaw_Test.should_fail_if_actual_is_not_canonical:81 ... Permission denied
[ERROR]   Paths_assertStartsWithRaw_Test.should_fail_if_other_is_not_canonical:92 ... Permission denied
[ERROR]   Paths_assertStartsWith_Test.should_pass_if_actual_is_not_canonical:112 ... Permission denied
[ERROR]   Paths_assertStartsWith_Test.should_pass_if_other_is_not_canonical:121 ... Permission denied
[ERROR] Tests run: 17343, Failures: 0, Errors: 20, Skipped: 47
```

With `mvn install -Dmaven.test.skip` it fails with:
```
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.6:check (default) on project assertj-core-groovy: Some files do not have the expected license header. Run license:
format to update them. -> [Help 1]
```
But it first installs assertj-core successfully.

**Comment by scordio** [comment]
> In case you are interested there are still failing tests, because by default on windows you need admin privileges to create symbolic links (because someone at Microsoft decided symbolic links are a security threat 🤦 this is not the first time I had this issue).

Ah! #3183 is another issue that I fixed but haven't backported 😅 will do that too in #4087.

**Comment by scordio** [comment]
> > This appears to be related to [#3996](https://github.com/assertj/assertj/issues/3996), which I partially fixed on `main` with [3941c9e](https://github.com/assertj/assertj/commit/3941c9e7c19cf4f3a7ddb8ecba6986a01429a3c1) but not on `3.x`, so I'll backport that commit.
> 
> This seems to have worked.

Actually, I haven't backported 3941c9e7 yet 🙃 but I might have rewritten or suppressed the root cause... I'll check it in #4088.

**Comment by scordio** [comment]
Done in 1cbc47274760f5fb4de6d177fe2f5cd373a60665.
